apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caching-platform-data
  namespace: caching-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd